name: Build

on: workflow_dispatch
  # pull_request:
  #   branches: [develop]

jobs:
  # run-commitlint-on-pr:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14.x
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: yarn

  #     - name: Validate all commits from PR
  #       run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  sanity-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn && npm run build

      - name: tscheck
        run: npm run tscheck --if-present

      - name: lint
        run: npm run lint --if-present

      - name: test
        run: npm run test --if-present
